/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package minicrm;

import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import minicrm.entity.Customer;
import minicrm.entity.Interaction;
import minicrm.entity.Representative;

/**
 *
 * @author ipd
 */
public class MainWindow extends javax.swing.JFrame {

    Database db;
    DefaultListModel<Representative> modelRepList = new DefaultListModel<>();
    DefaultListModel<Customer> modelCustomerList = new DefaultListModel<>();
    DefaultListModel<Interaction> modelInteractionList = new DefaultListModel<>();

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        try {
            db = new Database();
            initComponents();
            refreshRepList();
            refreshCustomerList();
            enableButtonWhenBothListsSelected();
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this,
                    "Failed to open database connection",
                    "Database error",
                    JOptionPane.ERROR_MESSAGE);
            System.exit(1);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dlgAddRep = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfFName = new javax.swing.JTextField();
        tfLName = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        dlgAddCustomer = new javax.swing.JDialog();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tfDlgFName = new javax.swing.JTextField();
        tfDlgLName = new javax.swing.JTextField();
        tfDlgAddress = new javax.swing.JTextField();
        tfDlgPostalCode = new javax.swing.JTextField();
        tfDlgPhoneNo = new javax.swing.JTextField();
        tfDlgSIN = new javax.swing.JTextField();
        btnDlgSave = new javax.swing.JButton();
        btnDlgCancel = new javax.swing.JButton();
        dlgInteraction = new javax.swing.JDialog();
        jLabel11 = new javax.swing.JLabel();
        lblForRepresentative = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstInteraction = new javax.swing.JList<>();
        jLabel14 = new javax.swing.JLabel();
        lblForCustomer = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        lblForRepName = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        lblForInteraction = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        TANotes = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        btnAddNote = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        TAAddNotes = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnInteraction = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstCustomerRep = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstFindCustomer = new javax.swing.JList<>();
        btnAddRep = new javax.swing.JButton();
        btnAddCustomer = new javax.swing.JButton();

        dlgAddRep.setModal(true);

        jLabel3.setText("First Name");

        jLabel4.setText("Last Name");

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dlgAddRepLayout = new javax.swing.GroupLayout(dlgAddRep.getContentPane());
        dlgAddRep.getContentPane().setLayout(dlgAddRepLayout);
        dlgAddRepLayout.setHorizontalGroup(
            dlgAddRepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgAddRepLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(dlgAddRepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dlgAddRepLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(btnSave)
                        .addGap(40, 40, 40)
                        .addComponent(btnCancel))
                    .addGroup(dlgAddRepLayout.createSequentialGroup()
                        .addGroup(dlgAddRepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(dlgAddRepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfFName, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                            .addComponent(tfLName))))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        dlgAddRepLayout.setVerticalGroup(
            dlgAddRepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgAddRepLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(dlgAddRepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfFName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(dlgAddRepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfLName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(dlgAddRepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnCancel))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        dlgAddCustomer.setModal(true);

        jLabel5.setText("First Name");

        jLabel6.setText("Last Name");

        jLabel7.setText("Address");

        jLabel8.setText("Postal Code");

        jLabel9.setText("Phone No.");

        jLabel10.setText("SIN");

        btnDlgSave.setText("Save");
        btnDlgSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDlgSaveActionPerformed(evt);
            }
        });

        btnDlgCancel.setText("Cancel");
        btnDlgCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDlgCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dlgAddCustomerLayout = new javax.swing.GroupLayout(dlgAddCustomer.getContentPane());
        dlgAddCustomer.getContentPane().setLayout(dlgAddCustomerLayout);
        dlgAddCustomerLayout.setHorizontalGroup(
            dlgAddCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgAddCustomerLayout.createSequentialGroup()
                .addGroup(dlgAddCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dlgAddCustomerLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(dlgAddCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel10))
                        .addGap(28, 28, 28)
                        .addGroup(dlgAddCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfDlgSIN, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                            .addComponent(tfDlgPhoneNo)
                            .addComponent(tfDlgPostalCode)
                            .addComponent(tfDlgAddress)
                            .addComponent(tfDlgLName)
                            .addComponent(tfDlgFName)))
                    .addGroup(dlgAddCustomerLayout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(btnDlgSave)
                        .addGap(46, 46, 46)
                        .addComponent(btnDlgCancel)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        dlgAddCustomerLayout.setVerticalGroup(
            dlgAddCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgAddCustomerLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(dlgAddCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfDlgFName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dlgAddCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfDlgLName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dlgAddCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tfDlgAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dlgAddCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tfDlgPostalCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dlgAddCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tfDlgPhoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dlgAddCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tfDlgSIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dlgAddCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDlgSave)
                    .addComponent(btnDlgCancel))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jLabel11.setText("Current Representative:");

        jLabel13.setText("List of interactions, sorted by date:");

        lstInteraction.setModel(modelInteractionList);
        lstInteraction.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstInteractionValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(lstInteraction);

        jLabel14.setText("Current Customer:");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Selected interaction details"));

        jLabel16.setText("Representative Name:");

        jLabel18.setText("Interaction Date:");

        jLabel20.setText("Notes:");

        TANotes.setColumns(20);
        TANotes.setRows(5);
        jScrollPane4.setViewportView(TANotes);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblForRepName, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblForInteraction, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblForRepName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblForInteraction, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addGap(21, 21, 21))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Add new interaction note"));

        btnAddNote.setText("Add new interaction note");
        btnAddNote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNoteActionPerformed(evt);
            }
        });

        TAAddNotes.setColumns(20);
        TAAddNotes.setRows(5);
        jScrollPane5.setViewportView(TAAddNotes);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAddNote, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAddNote)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout dlgInteractionLayout = new javax.swing.GroupLayout(dlgInteraction.getContentPane());
        dlgInteraction.getContentPane().setLayout(dlgInteractionLayout);
        dlgInteractionLayout.setHorizontalGroup(
            dlgInteractionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgInteractionLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(dlgInteractionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dlgInteractionLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblForRepresentative, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel13)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(dlgInteractionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(dlgInteractionLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblForCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27))
        );
        dlgInteractionLayout.setVerticalGroup(
            dlgInteractionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgInteractionLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(dlgInteractionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(dlgInteractionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(jLabel14)
                        .addComponent(lblForCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblForRepresentative, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(dlgInteractionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dlgInteractionLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dlgInteractionLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(20, 20, 20))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Customer Rep");

        jLabel2.setText("Find customer");

        btnInteraction.setText("M-C Interactions");
        btnInteraction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInteractionActionPerformed(evt);
            }
        });

        lstCustomerRep.setModel(modelRepList);
        lstCustomerRep.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstCustomerRepValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstCustomerRep);

        lstFindCustomer.setModel(modelCustomerList);
        lstFindCustomer.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstFindCustomerValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(lstFindCustomer);

        btnAddRep.setText("Add Rep");
        btnAddRep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddRepActionPerformed(evt);
            }
        });

        btnAddCustomer.setText("Add Customer");
        btnAddCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCustomerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(btnAddRep)))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 7, Short.MAX_VALUE)
                        .addComponent(btnAddCustomer))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(21, 21, 21)
                .addComponent(btnInteraction)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(btnInteraction, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddRep)
                    .addComponent(btnAddCustomer))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddRepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddRepActionPerformed
        // TODO add your handling code here:
        dlgAddRep.pack();
        dlgAddRep.setVisible(true);
    }//GEN-LAST:event_btnAddRepActionPerformed

    private void btnAddCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCustomerActionPerformed
        // TODO add your handling code here:
        dlgAddCustomer.pack();
        dlgAddCustomer.setVisible(true);
    }//GEN-LAST:event_btnAddCustomerActionPerformed

    private void btnDlgSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDlgSaveActionPerformed
        // TODO add your handling code here:
        String firstName = tfDlgFName.getText();
        String lastName = tfDlgLName.getText();
        String address = tfDlgAddress.getText();
        String postalCode = tfDlgPostalCode.getText();
        String phoneNumber = tfDlgPhoneNo.getText();
        String SIN = tfDlgSIN.getText();

        try {
            db.addCustomer(firstName, lastName, address, postalCode, phoneNumber, SIN);
            dlgAddCustomer.setVisible(false);
            refreshCustomerList();
            tfDlgFName.setText("");
            tfDlgLName.setText("");
            tfDlgAddress.setText("");
            tfDlgPostalCode.setText("");
            tfDlgPhoneNo.setText("");
            tfDlgSIN.setText("");
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this,
                    "Failed execute database query",
                    "Database error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnDlgSaveActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        String firstName = tfFName.getText();
        String lastName = tfLName.getText();
        try {
            db.addRep(firstName, lastName);
            dlgAddRep.setVisible(false);
            refreshRepList();
            tfFName.setText("");
            tfLName.setText("");
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this,
                    "Failed execute database query",
                    "Database error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        dlgAddRep.setVisible(false);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnDlgCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDlgCancelActionPerformed
        // TODO add your handling code here:
        dlgAddCustomer.setVisible(false);
    }//GEN-LAST:event_btnDlgCancelActionPerformed

    private void btnInteractionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInteractionActionPerformed
        // TODO add your handling code here:
        dlgInteraction.pack();
        dlgInteraction.setVisible(true);
        Representative rep = lstCustomerRep.getSelectedValue();
        lblForRepresentative.setText(rep.nameFirst + " " + rep.nameLast);
        Customer cust = lstFindCustomer.getSelectedValue();
        lblForCustomer.setText(cust.nameFirst + " " + cust.nameLast);
        modelInteractionList.clear();
        modelInteractionList.addElement(new Interaction(123,021,033, "2016/02/14", "good"));
    /*    try {
            ArrayList<Interaction> interactionList = db.getInteractions(cust.nameFirst, cust.nameLast, rep.nameFirst, rep.nameLast);
            modelInteractionList.clear();
            for (Interaction i : interactionList) {
                modelInteractionList.addElement(i);
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this,
                    "Failed execute database query",
                    "Database error",
                    JOptionPane.ERROR_MESSAGE);
        }*/
    }//GEN-LAST:event_btnInteractionActionPerformed

    private void lstCustomerRepValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstCustomerRepValueChanged
        // TODO add your handling code here:
        enableButtonWhenBothListsSelected();
    }//GEN-LAST:event_lstCustomerRepValueChanged

    private void lstFindCustomerValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstFindCustomerValueChanged
        // TODO add your handling code here:
        enableButtonWhenBothListsSelected();
    }//GEN-LAST:event_lstFindCustomerValueChanged

    private void lstInteractionValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstInteractionValueChanged
        // TODO add your handling code here:
        int idx = lstInteraction.getSelectedIndex();
        if (idx >= 0){
            lblForRepName.setText(lblForRepresentative.getText());
            Interaction I = modelInteractionList.get(idx);
            lblForInteraction.setText(I.date);
            TANotes.setText(I.notes);
            TANotes.setEditable(false);
            TAAddNotes.setText(I.notes);
            TAAddNotes.setEditable(true);
        }
    }//GEN-LAST:event_lstInteractionValueChanged

    private void btnAddNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNoteActionPerformed
        // TODO add your handling code here:
        int idx = lstInteraction.getSelectedIndex();
        Interaction I = modelInteractionList.get(idx);
        I.notes = TAAddNotes.getText();
    }//GEN-LAST:event_btnAddNoteActionPerformed

    private void refreshRepList() {
        try {
            ArrayList<Representative> repList = db.getAllReps();
            modelRepList.clear();
            for (Representative r : repList) {
                modelRepList.addElement(r);
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this,
                    "Failed execute database query",
                    "Database error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    private void refreshCustomerList() {
        try {
            ArrayList<Customer> customerList = db.getAllCustomers();
            modelCustomerList.clear();
            for (Customer c : customerList) {
                modelCustomerList.addElement(c);
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this,
                    "Failed execute database query",
                    "Database error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    private void enableButtonWhenBothListsSelected() {
        int idx1 = lstCustomerRep.getSelectedIndex();
        int idx2 = lstFindCustomer.getSelectedIndex();
        boolean enabled = idx1 >= 0 && idx2 >= 0;
        btnInteraction.setEnabled(enabled);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea TAAddNotes;
    private javax.swing.JTextArea TANotes;
    private javax.swing.JButton btnAddCustomer;
    private javax.swing.JButton btnAddNote;
    private javax.swing.JButton btnAddRep;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDlgCancel;
    private javax.swing.JButton btnDlgSave;
    private javax.swing.JButton btnInteraction;
    private javax.swing.JButton btnSave;
    private javax.swing.JDialog dlgAddCustomer;
    private javax.swing.JDialog dlgAddRep;
    private javax.swing.JDialog dlgInteraction;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lblForCustomer;
    private javax.swing.JLabel lblForInteraction;
    private javax.swing.JLabel lblForRepName;
    private javax.swing.JLabel lblForRepresentative;
    private javax.swing.JList<Representative> lstCustomerRep;
    private javax.swing.JList<Customer> lstFindCustomer;
    private javax.swing.JList<Interaction> lstInteraction;
    private javax.swing.JTextField tfDlgAddress;
    private javax.swing.JTextField tfDlgFName;
    private javax.swing.JTextField tfDlgLName;
    private javax.swing.JTextField tfDlgPhoneNo;
    private javax.swing.JTextField tfDlgPostalCode;
    private javax.swing.JTextField tfDlgSIN;
    private javax.swing.JTextField tfFName;
    private javax.swing.JTextField tfLName;
    // End of variables declaration//GEN-END:variables
}
